#!/bin/bash
args=( "$@" )
usegcc=yes
if [[ $# -eq 1 ]] && [[ $1 =~ ^@ ]]
then
  readarray a < <( cat ${1#?} | sed 's/\(^"\|"$\)//g' )
  set -- ${a[*]}
fi

if [[ $1 == --version ]] || [[ $1 == -Wl,--version ]]
then
  exec "$ANDROID_NDK/toolchains/$ANDROID_NDK_TOOLCHAIN/bin/arm-linux-androideabi-ld" --version
  exit 0
fi
if [[ $1 == -v ]] || [[ $1 == -Wl,-v ]]
then
  exec "$ANDROID_NDK/toolchains/$ANDROID_NDK_TOOLCHAIN/bin/arm-linux-androideabi-ld" -v
  exit 0
fi
if [[ $1 == --help ]] || [[ $1 == -Wl,--help ]]
then
  exec "$ANDROID_NDK/toolchains/$ANDROID_NDK_TOOLCHAIN/bin/arm-linux-androideabi-ld" --help
  exit 0
fi

while (( "$#" ));
do
  if [[ $1 == -r ]]
  then
    usegcc=no
    break
  fi
  shift
done

if [ "$usegcc" == "yes" ];
then
  exec "$ANDROID_NDK/toolchains/$ANDROID_NDK_TOOLCHAIN/bin/arm-linux-androideabi-gcc" "${args[@]}"
else
  exec "$ANDROID_NDK/toolchains/$ANDROID_NDK_TOOLCHAIN/bin/arm-linux-androideabi-ld" "$@"
fi

