/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_alpha_HaskellActivity */

#ifndef _Included_jp_alpha_HaskellActivity
#define _Included_jp_alpha_HaskellActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     jp_alpha_HaskellActivity
 * Method:    nativePipeStdout
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_alpha_HaskellActivity_nativePipeStdout
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jp_alpha_HaskellActivity
 * Method:    nativePipeStderr
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_alpha_HaskellActivity_nativePipeStderr
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jp_alpha_HaskellActivity
 * Method:    runHaskell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_alpha_HaskellActivity_runHaskell
  (JNIEnv *, jobject);

/*
 * Class:     jp_alpha_HaskellActivity
 * Method:    interrupt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_alpha_HaskellActivity_interrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
